wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715271586
    t:
      1:
      - 55
      - 95
      - 105
      2:
      - 55
      - 95
      - 105
      3:
      - 13
      - 14
      - 15
      - 23
      - 58
      4: 3.11.5
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
